id: IA1A98B3A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:48:40+00:00'
last_modified: '2022-06-08T05:24:45.755179+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ164
  title: ཀུན་ཁྱབ་རྡོ་རྗེ་དྲག་པོ་རྩལ་གྱི་སྤྱན་འདྲེན་བསྐང་བ་ཕྲིན་བཅོལ་དང་བཅས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5C86:
      image_group_id: I1CZ677
      title: Volume 1 of kun khyab rdo rje drag po rtsal gyi spyan 'dren bskang ba
        phrin bcol dang bcas pa
      total_pages: 34
      order: 1
      base_file: 5C86.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
